LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Robot.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Setup.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/TestMotorBackwardCmd.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/TestMotorForwardCmd.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/TestMotorStopCmd.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/TestController.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/opmodes/BasicAuto.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/opmodes/Test.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/TestSubsystem.java

validated all four motors on drivebase

Motor testing

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/TestController.java
build.dependencies.gradle

Updated button names to reflect the breaking change to disambiguate the XBox and PS4/5 controllers

Updated to TechnoLib 1.3.0

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/TestController.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/helpers/StartingPosition.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/opmodes/Test.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/TestSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/helpers/StartingPosition.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/helpers/StartingPosition.java

Renamed StartingPosition for the 'wing' section, autoformatted code

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Hardware.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Robot.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Setup.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/DriveCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/DriverController.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/opmodes/PlainDrive.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/DrivebaseSubsystem.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Twenty403Testing.java

We got a drivebase driving. Friday: IMU!

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Hardware.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Robot.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/DriveCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/DrivebaseSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/driving/JoystickDriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/driving/ResetGyroCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/DriverController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/JustDrivingTeleOp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

Copied a bunch of code from PowerPlay, then ripped out the yucky stuff with @braelynandthefrogs

driver relative driving works for 20403

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/ServoLeft.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/ServoRight.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/TestController.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/TestSubsystem.java

This is work students did on Tuesday and Friday to get a ServoTesting opmode going.

More stuff in the test bed

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/intake/EjectCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/intake/IntakeCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/intake/StopCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/IntakeTeleOp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/IntakeSubsystem.java

Students put together the Intake subsystem for 16750

---

FtcRobotController/src/main/AndroidManifest.xml
FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptAprilTag.java
FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptAprilTagEasy.java
FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptTensorFlowObjectDetection.java
FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/RobotAutoDriveToAprilTagOmni.java
FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/RobotAutoDriveToAprilTagTank.java
README.md
build.dependencies.gradle

Tested on kevbot2: doesn't require a driver station update :)

SDK 9.0.1 update

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelSelection.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelSelection.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/JustDrivingTeleOp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedWing.java

Not tested at all, but it appears to be building

More copy-pasta for auto

---

MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstants.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstantsRed.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Sixteen750Testing.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Twenty403Testing.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelRight.java

It all builds, and doesn't make anything worse...

Moving Maggie's work into main

---

build.gradle

This should speed up the checks by some measurable amount

Only build the two real bots for PR checks

---

MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstantsBlue.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Twenty403Testing.java

This hasn't been tested on the bot, but it's all under MeepMeep, so that's okay.

Stuff Braelyn did on Tuesday

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/PlacementSubsystem.java

Laksh and Bavjot finished this up (the untested skeleton), and it builds...

Placement subsystem

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/StagePixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/StagePixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/StagePixelRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/StagePixelSelection.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/StagePixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/StagePixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/StagePixelRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/StagePixelSelection.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkRedWing.java

Running on a bot (Still moving too far, but 'working')

Maggie's Amazing Autonomous Coding (MAAC)

---

MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstantsBlue.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstantsRed.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Sixteen750Testing.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Twenty403Testing.java

working to add left and right spike paths for stage red and blue

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/HangSubsystem.java

It builds. Nothing's wired up to the robot yet...

Hang subsystem10/10/2023

---

MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstantsBlue.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstantsRed.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Twenty403Testing.java

for stage red and blue 10/10/23

Successfully added left and right spike pixel push and parks 

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/DrivebaseSubsystem.java

Tested by students using KevBot 2.0

16750 auto testing and comments (auto is working)

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/PlacementSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/driving/DriveTestCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/driving/JoystickDriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/TestForwardBackward.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

Hopefully, I'm feeling well, but just in case, I'd like this stuff around for students

Added some comments with todos, plus a little code for logging magnitude

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/VisionPipeline.java

Harshini & Ximena got this all working, but with a camera on KevBot. We'll adjust numbers once we have a bot together.

now we can see both squares and red wing works yay 10/17/23

---

MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstantsBlue.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/AutoConstantsRed.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Sixteen750Testing.java
MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Twenty403Testing.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/StagePixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/StagePixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/StagePixelRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/StagePixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/StagePixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/StagePixelRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/WingPixelRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkBlueStage.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkBlueWing.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkRedStage.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkRedWing.java

Tested on KevBot, cuz 16750 drivebase is still not quite ready

A bunch of auto work from Maggie & Braelyn

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/ManualTeleOp.java

Also skipped creating the drive base & vision if not connected

Allocated the IntakeSubsystem, so it's not null

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/VisionPipeline.java

Tested on KevBot, not 20403, so rectangles likely to move, but color hue seems good and pixel minimum is also good.

blue now works yay [Harshini] 10/20/23

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/HangUp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/LeadScrewDown.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/LeadScrewUp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/HangSubsystem.java

Code builds, but since we still don't have a bot, no testing yet...

Subsystems: Adding the Hang subsystem

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Hardware.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Robot.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/LiftHighCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/LiftLowCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/LiftMidCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/TestController.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/PlacementSubsystem.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/TestSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/HangUp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/LeadScrewDown.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/LeadScrewUp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftHighCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftIntakeCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftLowCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftMediumCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/ManualTeleOp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/HangSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/PlacementSubsystem.java
settings.gradle

The PID stuff was tested on a bare motor, and appears to be doing something that looks right.

Lift stuff ready to merge

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/driving/NormalModeCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/driving/SnailModeCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/driving/TurboModeCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/DriverController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

This has been fully tested on kevbot. Maggie & Harshini did good work :)

Drivebase turbo/snail capabilities

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelSelection.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelSelection.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedWing.java

And it was working for the 20403 both (or at least, doing close to what we wanted it to do)

Auto on both bots

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/TriggerTestCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/TestController.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/opmodes/DumbOpMode.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/opmodes/Test.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/PlacementSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/hang/HangUp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/hang/LeadScrewDown.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/hang/LeadScrewUp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/HangSubsystem.java

(Students put it on the same branch as the trigger threshold test, which is in LearnBot)

Hang subsystem

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/DrivebaseSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/DroneSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/VisionSubsystem.java

And the 16750 bot drives straight, too

Working on subsystems: 10 24 2023

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/ForwardBackwardCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/ForwardBackwardSide.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/DrivebaseSubsystem.java

Tested on the wooden robot drivebase prototype

Harshini & Maggie's work on 16750

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/SingleController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ClawSubsystem.java

- Started copying PID into clawsubsystem
- Updated values for the claw
(Tested on the 20403 bot)

- Commented out errors related to non-existant Elbow servo

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/HangSubsystem.java

*Not* tested on a bot (Hang isn't done yet)

Hang values

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java

Binded controlls for Arm in the claw subsystem

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java

(Cleaned up to make things a little easier to comment out/merge)

Binding controls for Arm in the claw subsystem

---

MeepMeepTesting/src/main/java/com/example/meepmeeptesting/Twenty403Testing.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/ForwardBackwardCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/hang/HangUp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/hang/LeadScrewDown.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/hang/LeadScrewUp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/ForwardBackwardSide.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/TestForwardBackward.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

This is a bunch of auto code that was validated on the wood 16750 prototype by Maggie & Harshini

16750 auto maggie and harshini

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/hang/HangDown.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/hang/HangStop.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/hang/HangUp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/hang/LeadScrewDown.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/hang/LeadScrewStop.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/hang/LeadScrewUp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/hang/HangUp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/HangSubsystem.java

Bhavjot got the hang stuff tested with some different hardware. Numbers are probably off, but it functions as expected...

Hang validation10 28 23

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ClawSubsystem.java

This has a semi-functional arm PID controller working (PID is not well tuned, but doing okay...)

Braelyn pid tuning

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/claw/ArmDecrementCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/claw/ArmIncrementCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ClawSubsystem.java

The small increment work isn't functioning (I suspect it's because there are multiple commands bound to the same button)

PID/ARM stuff for 20403 from 10/31

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/VisionCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/claw/ArmNeuteralPosition.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ClawSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/HangSubsystem.java

This also includes eliminating contention for a particular button

Added hang resting position and arm neutral position

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ClawSubsystem.java

We can move slightly down...sometimes. Still can't move slightly up.

Made some arm adjustments, still not quite right

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/VisionPipeline.java

Tested sitting in the red wing side

Vision constants for 20403 are good

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/VisionCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/claw/ArmDecrementCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/claw/ArmIncrementCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/claw/ArmNeutralPosition.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ClawSubsystem.java

I cleaned up some of the arm code, ran the auto-formatter, and fixed "neutral" 😃

Arm cleanup 11 2

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java

I blame Colin for the title of this PR :D He's a minor, and is not legally responsible for this statement.

Changed buttons to match Colin's every whim. Erwin must cope and seethe

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/ForwardBackwardCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/SideAndBackCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/ForwardBackwardCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/SideAndBackCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/ForwardBackward.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/Sideways.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

(still needing work, its jerky) Maggie and Harshini 11/3/23

20403 auto pathing configuration gear ratio and lateral multiplier

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/HangStop.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/DualTeleOp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/HangSubsystem.java

Tested as best as we can without hardware

16750 hang subsystem 11 3 23

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DroneSubsystem.java

Drone & Snail is slower

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/driving/SlowCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/driving/TurboCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/DriverController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/SingleController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/DrivebaseSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/IntakeSubsystem.java

Have turbo added in code - but needs extra testing

Got 16750 Intake wheels working

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/DriverController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

Button swap

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/driving/NormalModeCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/driving/SnailModeCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/driving/TurboModeCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/DriverController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/SingleController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/DrivebaseSubsystem.java

Hoda's 16750 drive base stuff: Validated on hardware!

Added Turbo and Snail

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/driving/JoystickDriveCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/DriverController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/DrivebaseSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/driving/JoystickDriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/DriverController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java
package-lock.json
yarn.lock

rotation and driveStraight combined

---

RoadRunnerQuickStart/src/main/java/org/firstinspires/ftc/teamcode/drive/SampleMecanumDrive.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/Sideways.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

This has been running on the 20403 bot for updating for new motors

Auto configuration with new motors Maggie

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/TwoDeadWheelLocalizer.java

initial odometry reports useful information
-Gabriel Wong

Finish odo

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/driving/JoystickDriveCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/DriverController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/TwoDeadWheelLocalizer.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/VisionPipeline.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/VisionSubsystem.java

We need to get the odo stuff working, as the bot drives very crazy with it enabled.

Vision locations updated, odo functional but wrong

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/TwoDeadWheelLocalizer.java

At this point, we'll need to retune the drive base, but it's driving alright forward/backward, side-to-side, and forward to a heading and back
(Validated on 20403 hardware)

Odometry working

---

scripts/helpers/branch.ts

Fixed a bug in the scripts

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java

Just some minor testing with the odo pods from Maggie

20403 auto pathing stuff with odo pods

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

Maggie and Harshini's new PID and Auto numbers

---

FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/internal/FtcRobotControllerActivity.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/RecordFinalHeading.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/helpers/HeadingHelper.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/TwoDeadWheelLocalizer.java

Gabriel worked on this stuff to allow us to save the head at the end of auto and use it as "ahead" when Tele is started

Adding auto => tele communication for bot heading

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/IntakeSubsystem.java

Changed 16750 intake speed and directions because they were backwards

---

TODO.md

Punchlist for LM2

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/ElbowDecrementCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/ElbowIncrementCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/ArmTestController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/ArmTestingTeleOp.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ArmSubsystem.java

This is all the work Harshini & Braelyn did on Saturday. Tested on 20403, and "working" :)

Braelyn 2023.11.25 elbow and arm vals

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedWing.java

Updated vision stuff to be selection commands

Vision selection commands

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkBlueStage.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkBlueWing.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkRedStage.java

vision works now, did not change square locations
12-1-23 harshini

removed slashes from vision code in auto

---

TODO.md
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueStage.java

Maggie's auto tuning from 12/2

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Robot.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/DroneLaunch.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/DroneStart.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/TestingController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/DualTeleOp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/ServoTestingOpMode.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkBlueStage.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/auto/PixelThenParkBlueWing.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/DroneSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/IntakeSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ArmSubsystem.java

Drone tested and works on servo testing opmode. Haven't binded on driver/operator controls only testing controller. Not attached to the bot yet

Drone subsystem testing

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/SafetySubsystem.java

still work in progress
not integrated with any code

started safety subsystem - Harshini

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/HangSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/TwoDeadWheelLocalizer.java

Hang Subsystem for 16750

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelPlaceLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelPlaceMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelPlaceRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelPlaceSelection.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelPlaceLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelPlaceMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelPlaceRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelPlaceSelection.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelPlaceLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelPlaceMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelPlaceRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelPlaceSelection.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelPlaceLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelPlaceMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelPlaceRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelPlaceSelection.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PixelThenParkRedWing.java

Maggie's started working on different parking & pixel placement

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Hardware.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/OnlyMotorRobot.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Setup.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/AnalogMotorControlCmd.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/AnalogMotorDecCmd.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/AnalogMotorIncCmd.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/AnalogMotorToggleControlCmd.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/AnalogMotorToggleStopModeCmd.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/MotorController.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/TestController.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/opmodes/AnalogMotorTest.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/MotorTestSubsystem.java
yarn.lock

Added a 'Just move a motor around' op mode in LearnBot

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/HangDown.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/HangUp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/LeadScrewStop.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/HangSubsystem.java

Not tested on bot, but who cares?

Bhavjot's awesome hang subsystem

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/SafetySubsystem.java

made changes to logic, made it so that we can now see what broke auto odo pods can now be seen in telemetry - Harshini 12/16

Safety Subsystem progress

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Hardware.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/hang/HangNeutral.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/ServoTestingOpMode.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/DroneSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/HangSubsystem.java

16750 Hang tested and added the neutral position class

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/ArmHoldCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftIntakeSequential.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftLowSequential.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftMediumSequential.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/ScoreHoldCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/ServoOutputs.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/PlacementSubsystem.java

Hoda's work on Friday. Not absolutely correct, but functioning.

12 22 16750

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Hardware.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Robot.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/EnterHangCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/HangDownCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/HangStopCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/HangUpCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/LeaveHangCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/DriverController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ArmSubsystem.java

This stuff mostly worked, and it's blocking Maggie, so we need it in Main.

Braelyn 2024.01.02 new arm motor

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/ArmFirstLineCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/ArmSecondLineCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/ArmThirdLineCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ArmSubsystem.java

added slurp to first, second and unused third line.

pid fixes, tested and works. fixed wrist and shoulder vals

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/JustDrivingTeleOp.java

This was tested on the bot, and is part of what is in Braelyn's branch at 616e4e1

Grabbed Braelyn's change for teleop

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/SafetyStartCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/SafetyStopCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/SafetyTestOdoFCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/SafetyTestOdoRCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/SafetyTestWheelFLCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/SafetyTestWheelFRCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/SafetyTestWheelRLCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/SafetyTestWheelRRCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/SafetyTestController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/ForwardBackward.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/SafetySubsystem.java

This stuff isn't yet widely used (or tested) but isn't used at all yet on the bot, so I just want to get it in main.

20403 safety subsystem work

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/DualTeleOp.java

Fixed a couple minor things: works on bot

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftIntakeSequential.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftLowSequential.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/LiftMediumSequential.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/ScoreHoldCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/ScoreHoldSequential.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/ScoreServoFlatCommand.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/placement/ServoIntakes.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/TestingController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/DualTeleOp.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/opmodes/ServoTestingOpMode.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/IntakeSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/PlacementSubsystem.java

Push stuff from yesterday to main

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/ParallelCarry.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/ParallelIntake.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/ParallelPlacement.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/ParkCenterPositioning.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelIntake.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelPlaceMiddle.java

also added some new testing commands for intaking pixels

20403 auto tested on the bot

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/SafetySubsystem.java

20403 safety subsystem 12 16

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelPlaceLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelPlaceMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelPlaceRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelPlaceLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelPlaceMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelPlaceRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelPlaceLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelPlaceMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelPlaceRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelPlaceLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelPlaceMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelPlaceRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/SafetySubsystem.java

20403 auto testing, tweaking constants and added some wait commands

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/ShoulderLargeDecrementCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/ShoulderLargeIncrementCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ArmSubsystem.java

Last minute changes braelyn

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/PixelScoring.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/BlueWingParkCenter.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelPlaceLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelPlaceMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelPlaceRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/PlacementSubsystem.java

All ye olde changes from ye olde interleagues

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelPlaceMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/StagePixelRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/blue/WingPixelRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/StagePixelRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelLeft.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelMiddle.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/WingPixelRight.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushParkCenterBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushParkCenterRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushParkCornerBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceCornerRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCenterBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCenterBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCenterRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCenterRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCornerBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCornerBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCornerRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCornerRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/SafetySubsystem.java

20403 Changes at Interleagues by Maggie :)

20403 interleagues changes

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/AutoConstants.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/BlueWingParkCenter.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelPlaceLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelPlaceMiddle.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/blue/WingPixelPlaceRight.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/commands/auto/red/StageParallelLeft.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/Setup.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/arm/ArmSecondLineCommand.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ArmSubsystem.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

I'm assuming that we'll have more code tonight, but this is what thefrogs & yinn did over the past couple weeks.

This is the starting point for WCI

---

Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/controls/OperatorController.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/subsystems/PlacementSubsystem.java

The edits for WCI from yinn on Friday

Stuff from Yinn

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/AutoConstants.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/commands/auto/red/SplineWingPushPlacePark.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushParkCenterBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushParkCenterRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushParkCornerBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceCornerRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCenterBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCenterRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCenterRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCornerBlueStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCornerBlueWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCornerRedStage.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/PushPlaceParkCornerRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/opmodes/auto/SplineTestRedWing.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/ArmSubsystem.java
build.gradle
gradle/wrapper/gradle-wrapper.properties
package.json

Getting this stuff into main. Hopefully it's all working 😬

20403 auto 6 14

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/VisionPipeline.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/VisionSubsystem.java
Sixteen750/src/main/java/org/firstinspires/ftc/sixteen750/Setup.java

This looks like some good stuff a student was working on. Merge it.

Learnbot vision

---

Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/DriverController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/controls/OperatorController.java
Twenty403/src/main/java/org/firstinspires/ftc/twenty403/subsystems/DrivebaseSubsystem.java

Slowed the peak speed down. Seems safe enough. Let's keep it.

The Frog Queen reduced damage 4 years olds can do when driving Flamingo

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/FlywheelSubsystem.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/IntakeSubsystem.java

Not sure if this builds alright, but it looks okay. Let's merge it.

Flywheel and intake subsystems for outreach bot

---

LearnBot/src/main/java/org/firstinspires/ftc/learnbot/ClawAndWristBot.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/ClawDecCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/ClawIncCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/WristDecCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/commands/WristIncCommand.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/controllers/ClawAndWristController.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/opmodes/ClawAndWristTele.java
LearnBot/src/main/java/org/firstinspires/ftc/learnbot/subsystems/ClawAndWristSubsystem.java

Claw and Wrist teleop + bot + commands
